version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

install:
  - choco install -y jdk8
  - choco install -y maven

cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.ivy2'
  - '%USERPROFILE%\.sbt'
  - bin

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: iex build\windows.ps1